server:
  port: 8083
spring:
  datasource:
    username: root
    password: root123456
    url: jdbc:mysql:///foolish?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0 # 设置数据库索引为0 默认为0
    password: # 密码为空
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 2 # 连接池中的最小空闲连接
    timeout: 2000 # 连接超时时间（毫秒）

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.foolish.swaggerdemo.entity




